"""Offline financial research analyst demo package."""

from financial_research.metrics import (
    BenchmarkSensitivity,
    FundamentalSnapshot,
    FundamentalsSummary,
    FundamentalsTrend,
    MovingAverageTrend,
    PerformanceSummary,
    PricePoint,
    build_risk_notes,
    load_fundamental_history,
    load_fundamental_snapshot,
    load_price_history,
    render_research_brief,
    render_research_brief_html,
    summarize_fundamentals,
    summarize_fundamentals_trend,
    summarize_moving_average_trend,
    summarize_benchmark_sensitivity,
    summarize_price_history,
)

__all__ = [
    "BenchmarkSensitivity",
    "FundamentalSnapshot",
    "FundamentalsSummary",
    "FundamentalsTrend",
    "MovingAverageTrend",
    "PerformanceSummary",
    "PricePoint",
    "build_risk_notes",
    "load_fundamental_history",
    "load_fundamental_snapshot",
    "load_price_history",
    "render_research_brief",
    "render_research_brief_html",
    "summarize_fundamentals",
    "summarize_fundamentals_trend",
    "summarize_moving_average_trend",
    "summarize_benchmark_sensitivity",
    "summarize_price_history",
]
